### ISSUE TITLE
whitespace variants

### ISSUE THREAD

**Issue by torstenroeder** [NesbiDevelopment/Variance-Viewer#2]
In the TEI download I sometimes see apparatus entries like:

```
<app>
   <lem>musikalischen</lem>
   <rdg>musikalischen </rdg>
</app>
```

These variants differ only by one whitespace character and should not be variants at all. They are not displayed in the Variance Viewer, which is totally correct, but they occur only in the download.

**Comment by torstenroeder** [comment]
Ok, it seems that these variants correspond to the "separation" type (displays if checked in the Variance Viewer). How do these occur? Is it possible to exclude them in the download file?

**Comment by torstenroeder** [comment]
After some serious thinking (thanks to my colleague): WS variants should generally remain.

**Comment by sinabock** [comment]
There are two ways that lead to entries like this:

> ```
> <app>
>    <lem>musikalischen</lem>
>    <rdg>musikalischen </rdg>
> </app>
> ```


1)	The variants differ by an additional space (at the beginning, in the middle or at the end of the lemma). This should be a variant.

2)	The variants differ by a a soft break (↵ which marks the end of a line or a paragraph). If possible - these soft breaks should not be treated as variants.

**Comment by NesbiDevelopment** [comment]
This seems to be a combination of issue #1  and #3

The output does highly likely include a SEPARATION Variance (that is normally set to hidden in the view)
This ``↵`` will (most likely) be displayed as a space, if the XML is viewed in a programming with pretty print (e.g. Chrome or Firefox)

The output must contain the variance type, which I'm currently working on fixing. (Issue #1)

I'm not planning on removing the separation variance, but I'm planning on adding the option of downloading only selected variances (and maybe by default disable separation). (Issue #3)

I'll close this issue and refer to #1 and #3, in which I'll pust future updates.
